# Base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Port number
EXPOSE 3000
COPY . .

# Install app dependencies
COPY package*.json ./
RUN npm install

# Start the server
CMD ["npm", "run", "start:debug"]
